
logging:
  level:
    com.app.mapper: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mybatis/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imy
    username: root
    password: Apache001
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterAccess=3s

